
import 'dotenv/config'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { CartProvider } from './context/CartContext';
import 'react-toastify/dist/ReactToastify.css';
import { Toaster } from 'sonner'

import {
  ClerkProvider
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body >
          <CartProvider>
            <main className="max-w-screen-xl mx-auto">
              {children}
              <Toaster richColors />
            </main>
          </CartProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
